# -*- mode: python ; coding: utf-8 -*-
import sys
sys.setrecursionlimit(5000)

block_cipher = None

a = Analysis(
    ['./src/vims/app/__main__.py'],
    pathex=['./src/vims/app'],
    paths=[],
    binaries=[],
    hiddenimports=['main',
    'databases',
    'databases.backends',
    'asyncio',
    'asyncio.base_events',
    'base_events',
    'backends',
    'databases.backends.sqlite',
    'databases.backends.postgres',
     'databases.backends.mysql',
    'databases.backends.asyncmy',
    'asyncmy.constants.ER',
    'asyncmy.constants.SERVER_STATUS',
    'asyncmy.constants.COMMAND',
    'asyncmy.constants.CR',
    'asyncmy.contexts',
    'postgres',
    'sqlite',
    'asyncmy',
    'asyncmy.auth',
    'asyncmy.structs',
    'asyncmy.charset',
    'asyncmy.cursors',
    'asyncmy.constants.COLUMN',
        'asyncmy.converters',
        'asyncmy.constants.FIELD_TYPE',
        'asyncmy.optionfile',
        'asyncmy.errors',
        'asyncmy.pool',
        'asyncmy.protocol',
        'asyncmy.structs',
        'asyncmy.version',
    'passlib.handlers.bcrypt',
    'asyncpg.pgproto.pgproto'],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='vims',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='vims',
)
