#  Copyright (c) 2013 - 2025. The Johns Hopkins University Applied Physics Laboratory LLC
#

from vims.app.permissions import Permission
from vims.app.roles import Role

roles = {
    Role.ADMIN: [
        Permission.ADMIN,
    ],
    Role.DEVELOPER: [
        Permission.READ_USERS,
        Permission.CREATE_USER,
        Permission.READ_USER,
        Permission.UPDATE_USER,
        Permission.UPDATE_USER_PASSWORD,
        Permission.DELETE_USER,
        Permission.READ_ROLES,
        Permission.CREATE_GROUP,
        Permission.READ_GROUPS,
        Permission.UPDATE_GROUP,
        Permission.DELETE_GROUP,
        Permission.READ_DATASETS_ALL,
        Permission.CREATE_DATASET,
        Permission.READ_DATASET_ALL,
        Permission.UPDATE_DATASET,
        Permission.DELETE_DATASET,
        Permission.READ_DATASOURCES,
        Permission.CREATE_DATASOURCE,
        Permission.READ_DATASOURCE,
        Permission.UPDATE_DATASOURCE,
        Permission.DELETE_DATASOURCE,
        Permission.READ_VISUALIZATIONS,
        Permission.CREATE_VISUALIZATION,
        Permission.READ_VISUALIZATION,
        Permission.UPDATE_VISUALIZATION,
        Permission.DELETE_VISUALIZATION,
        Permission.READ_MAPS,
        Permission.CREATE_MAP,
        Permission.UPDATE_MAP,
        Permission.DELETE_MAP,
    ],
    Role.USER: [
        Permission.READ_DATASET_SHARED,
        Permission.READ_DATASETS_SHARED,
        Permission.READ_VISUALIZATIONS,
        Permission.CREATE_VISUALIZATION,
        Permission.READ_VISUALIZATION,
        Permission.UPDATE_VISUALIZATION,
        Permission.DELETE_VISUALIZATION,
        Permission.READ_DATASOURCES,
        Permission.READ_DATASOURCE,
        Permission.CREATE_DASHBOARD,
        Permission.UPDATE_DASHBOARD,
        Permission.DELETE_DASHBOARD,
        Permission.READ_DASHBOARD,
        Permission.READ_DASHBOARDS,
        Permission.READ_MAPS,
    ],
    Role.VISUALIZATION_CREATOR: [
        Permission.READ_DATASETS_ALL,
        Permission.READ_DATASET_ALL,
        Permission.READ_DATASET_SHARED,
        Permission.READ_DATASETS_SHARED,
        Permission.READ_VISUALIZATIONS,
        Permission.CREATE_VISUALIZATION,
        Permission.READ_VISUALIZATION,
        Permission.UPDATE_VISUALIZATION,
        Permission.DELETE_VISUALIZATION,
    ],
}
