#  Copyright (c) 2013-2025. The Johns Hopkins University Applied Physics Laboratory LLC
#
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# NO WARRANTY.   THIS MATERIAL IS PROVIDED "AS IS."  JHU/APL DISCLAIMS ALL
# WARRANTIES IN THE MATERIAL, WHETHER EXPRESS OR IMPLIED, INCLUDING (BUT NOT
# LIMITED TO) ANY AND ALL IMPLIED WARRANTIES OF PERFORMANCE,
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT OF
# INTELLECTUAL PROPERTY RIGHTS. ANY USER OF THE MATERIAL ASSUMES THE ENTIRE
# RISK AND LIABILITY FOR USING THE MATERIAL.  IN NO EVENT SHALL JHU/APL BE
# LIABLE TO ANY USER OF THE MATERIAL FOR ANY ACTUAL, INDIRECT,
# CONSEQUENTIAL, SPECIAL OR OTHER DAMAGES ARISING FROM THE USE OF, OR
# INABILITY TO USE, THE MATERIAL, INCLUDING, BUT NOT LIMITED TO, ANY DAMAGES
# FOR LOST PROFITS.

from enum import Enum


class Settings(Enum):
    HOST = "HOST"
    PORT = "PORT"
    ENVIRONMENT = "ENVIRONMENT"
    DATABASE_URL = "DATABASE_URL"
    SQL_DATABASE_URL = "DATABASE_URL"
    DATABASE_NAME = "DATABASE_NAME"
    TOKEN_EXPIRES = "TOKEN_EXPIRES"
    JWT_SECRET_KEY = "JWT_SECRET_KEY"
    JWT_ALGORITHM = "JWT_ALGORITHM"
    ENCRYPTION_KEYS = "ENCRYPTION_KEYS"
    ETL_CONNECTION_URL = "ETL_CONNECTION_URL"
    ETL_DATA_FOLDER = "AIRFLOW_DATA_FOLDER"
    ETL_PRIMARY_KEY_COLUMN_NAME = "vims_primary_key"
    MOBILE_ETL_ENCRYPTION_KEY = "MOBILE_ETL_ENCRYPTION_KEY"
    RUN_MODE = "RUN_MODE"
    LOGIN_ATTEMPTS = "LOGIN_ATTEMPTS"
    LOGIN_LOCK_TIMEOUT_MINS = "LOGIN_LOCK_TIMEOUT_MINS"
    MAIL_SERVER_HOST = "MAIL_SERVER_HOST"
    MAIL_SERVER_PORT = "MAIL_SERVER_PORT"
    MAIL_SERVER_ADDRESS = "MAIL_SERVER_ADDRESS"
    FRONTEND_BASE_URL = "FRONTEND_BASE_URL"
